ktor:
  application:
    modules:
      - com.youchunmaru.ApplicationKt.module
  deployment:
    port: 8080
  development: true
jwt:
  audience: "jwt"
  issuer: "http://0.0.0.0:8080/"
  realm: "compass"
  secret: "secret"
db:
  url: "jdbc:mysql://localhost:3306/compass_db"
  user: "root"
  driver: "com.mysql.cj.jdbc.Driver"
  password: "root"